In [ ]:
import pandas as pd
CSV_PATH = "csv.csv"

def load_data(csv_path):
    return pd.read_csv(csv_path)

crops = load_data(CSV_PATH)
crops.head()

state       district  ... max_price modal_price
0  Andaman and Nicobar  South Andaman  ...      8000        7000
1  Andaman and Nicobar  South Andaman  ...      5500        5000
2  Andaman and Nicobar  South Andaman  ...      8000        7000
3  Andaman and Nicobar  South Andaman  ...      8000        7000
4  Andaman and Nicobar  South Andaman  ...    130000      120000

[5 rows x 9 columns]

In [ ]:
crops.drop("arrival_date",axis=1,inplace=True)

In [ ]:
crops.isna().sum()#No missing data

state          0
district       0
market         0
commodity      0
variety        0
min_price      0
max_price      0
modal_price    0
dtype: int64

In [ ]:
for label, cols in crops.items():
    if pd.api.types.is_string_dtype(cols):
        crops[label] = cols.astype("category").cat.as_ordered()
        crops[label] = crops[label].cat.codes

0       Andaman and Nicobar
1       Andaman and Nicobar
2       Andaman and Nicobar
3       Andaman and Nicobar
4       Andaman and Nicobar
               ...         
2233            West Bengal
2234            West Bengal
2235            West Bengal
2236            West Bengal
2237            West Bengal
Name: state, Length: 2238, dtype: object
0        South Andaman
1        South Andaman
2        South Andaman
3        South Andaman
4        South Andaman
             ...      
2233    Uttar Dinajpur
2234    Uttar Dinajpur
2235    Uttar Dinajpur
2236    Uttar Dinajpur
2237    Uttar Dinajpur
Name: district, Length: 2238, dtype: object
0       Port Blair
1       Port Blair
2       Port Blair
3       Port Blair
4       Port Blair
           ...    
2233      Islampur
2234      Islampur
2235       Raiganj
2236       Raiganj
2237       Raiganj
Name: market, Length: 2238, dtype: object
0                  Amaranthus
1              Banana - Green
2       Bhindi(Ladies Finger)
3            

In [ ]:
crops.info()#all categorical data now

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   state         2238 non-null   category
 1   district      2238 non-null   category
 2   market        2238 non-null   category
 3   commodity     2238 non-null   category
 4   variety       2238 non-null   category
 5   arrival_date  2238 non-null   category
 6   min_price     2238 non-null   int64   
 7   max_price     2238 non-null   int64   
 8   modal_price   2238 non-null   int64   
dtypes: category(6), int64(3)
memory usage: 112.8 KB


In [ ]:
crops.head()

state       district  ... max_price modal_price
0  Andaman and Nicobar  South Andaman  ...      8000        7000
1  Andaman and Nicobar  South Andaman  ...      5500        5000
2  Andaman and Nicobar  South Andaman  ...      8000        7000
3  Andaman and Nicobar  South Andaman  ...      8000        7000
4  Andaman and Nicobar  South Andaman  ...    130000      120000

[5 rows x 9 columns]

In [ ]:
crops.head()

state  district  market  ...  min_price  max_price  modal_price
0      0       153     246  ...       6000       8000         7000
1      0       153     246  ...       4500       5500         5000
2      0       153     246  ...       6000       8000         7000
3      0       153     246  ...       6000       8000         7000
4      0       153     246  ...     110000     130000       120000

[5 rows x 8 columns]

In [ ]:
crops.market.cat.

In [ ]:
crops.commodity.cat.categories

Index(['Amaranthus', 'Amla(Nelli Kai)', 'Amphophalus', 'Apple',
       'Arecanut(Betelnut/Supari)', 'Arhar (Tur/Red Gram)(Whole)',
       'Arhar Dal(Tur Dal)', 'Ashgourd', 'Bajra(Pearl Millet/Cumbu)', 'Banana',
       ...
       'Tobacco', 'Tomato', 'Turmeric', 'Turmeric (raw)', 'Turnip',
       'Water Melon', 'Wheat', 'Wheat Atta', 'White Pumpkin', 'Wood'],
      dtype='object', length=156)

In [ ]:
crops.variety.cat.categories

Index([' Subabul', '(Red Nanital)', '1001', '1009 Kar', '1121', '147 Average',
       '1st Sort', '2nd Sort', '777 New Ind', '95/5',
       ...
       'Water Melon', 'Wheat Atta', 'White', 'White Ponni', 'White Pumpkin',
       'Whole', 'Yellow', 'Yellow (Black)', 'api', 'other'],
      dtype='object', length=218)

In [ ]:
#calculate min prices
crops_min = crops.drop("max_price",axis=1)
crops_min = crops.drop("modal_price",axis=1)
crops_min.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   state      2238 non-null   int8 
 1   district   2238 non-null   int16
 2   market     2238 non-null   int16
 3   commodity  2238 non-null   int16
 4   variety    2238 non-null   int16
 5   min_price  2238 non-null   int64
 6   max_price  2238 non-null   int64
dtypes: int16(4), int64(2), int8(1)
memory usage: 54.8 KB


In [ ]:
#df for min prices predictions
crops_min.drop("max_price",axis=1,inplace=True)
crops_min.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   state      2238 non-null   int8 
 1   district   2238 non-null   int16
 2   market     2238 non-null   int16
 3   commodity  2238 non-null   int16
 4   variety    2238 non-null   int16
 5   min_price  2238 non-null   int64
dtypes: int16(4), int64(1), int8(1)
memory usage: 37.3 KB


In [ ]:
#train a model for the min prices now?
from sklearn.model_selection import train_test_split

X = crops_min.drop("min_price",axis=1)
Y = crops_min["min_price"]

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1)
X.head()

state  district  market  commodity  variety
0      0       153     246          0       17
1      0       153     246         10       30
2      0       153     246         18       39
3      0       153     246         19      148
4      0       153     246         22      148

In [ ]:
len(X_train), len(X_test), len(Y_train), len(Y_test)#SEEMS GOOD?
#CALM

(1790, 448, 1790, 448)

In [ ]:
import numpy as np
#FOREST REGRESSOR?
#AYT
np.random.state = 1
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
#we can tune later?
model.fit(X_train,Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [ ]:
np.random.state = 1
from sklearn.model_selection import cross_val_score
cross_val_score(model, X, Y, cv=5, scoring='neg_mean_squared_error')

array([-48699820.060773  ,  -7638877.73005746,  -4716265.90106964,
        -1491022.85725183,  -3168015.87261397])

In [ ]:
~~

SyntaxError: ignored

In [ ]:
X_train.head()

state  district  market  commodity  variety
982      16        56      34         24      148
638      10       160     157         18      148
2103     25        31      15        118      113
1468     22       143      39         31      148
737      12        92     160         40      148

In [ ]:
Y_train.head()

982     1400
638     2300
2103     540
1468    2500
737     1400
Name: min_price, dtype: int64

In [ ]:
X_train[:1]

state  district  market  commodity  variety
982     16        56      34         24      148

In [ ]:
model.predict(X_train[:1])

array([1195.])

In [ ]:
from sklearn.model_selection import GridSearchCV
np.random.state = 1
grid_data = {"max_depth":[6,8,10],
             "n_estimators":[5,10,15],
             "max_features":[3,4,5],
             "min_samples_split":[1,2,3,4]}

grid_model = GridSearchCV(RandomForestRegressor(),param_grid=grid_data,scoring="neg_root_mean_squared_error",cv=5,verbose=True,n_jobs=-1)
grid_model.fit(X,Y)
"""
bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False
                      """

Fitting 5 folds for each of 108 candidates, totalling 540 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 128 tasks      | elapsed:    3.5s
[Parallel(n_jobs=-1)]: Done 540 out of 540 | elapsed:   13.3s finished


"\nbootstrap=True, ccp_alpha=0.0, criterion='mse',\n                      max_depth=None, max_features='auto', max_leaf_nodes=None,\n                      max_samples=None, min_impurity_decrease=0.0,\n                      min_impurity_split=None, min_samples_leaf=1,\n                      min_samples_split=2, min_weight_fraction_leaf=0.0,\n                      n_estimators=100, n_jobs=None, oob_score=False,\n                      random_state=None, verbose=0, warm_start=False\n                      "

In [ ]:
grid_model.best_params_

{'max_depth': 8, 'max_features': 5, 'min_samples_split': 3, 'n_estimators': 15}

In [ ]:
grid_model.predict(X_train[:1])

array([1108.68472676])

In [ ]:
X_test.head()

state  district  market  commodity  variety
1595     23         0     269         66      123
1447     20       172     274        105      148
1138     18       106     187          9       31
535      10        95      90         24      148
1578     23         0     150         97      137

In [ ]:
Y_test.head()

1595    4900
1447    1750
1138    1300
535     2200
1578    2600
Name: min_price, dtype: int64

In [ ]:
grid_model.predict(X_test[:5])

array([3144.15432706, 1581.75908869, 1801.10347809, 2218.2011739 ,
       2798.41112352])

In [ ]:
min_model = RandomForestRegressor(max_depth=8, max_features= 5, min_samples_split= 3, n_estimators=15)
min_model.fit(X,Y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=8, max_features=5, max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=3, min_weight_fraction_leaf=0.0,
                      n_estimators=15, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [ ]:
import joblib
filename="min_price_model.sav"
joblib.dump(min_model,filename)

['min_price_model.sav']

In [ ]:
#create max price model



































#calculate max price
crops_max = crops.drop("min_price",axis=1)
crops_max = crops.drop("modal_price",axis=1)
crops_max.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   state      2238 non-null   int8 
 1   district   2238 non-null   int16
 2   market     2238 non-null   int16
 3   commodity  2238 non-null   int16
 4   variety    2238 non-null   int16
 5   min_price  2238 non-null   int64
 6   max_price  2238 non-null   int64
dtypes: int16(4), int64(2), int8(1)
memory usage: 54.8 KB


In [ ]:
crops_max.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2238 entries, 0 to 2237
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   state      2238 non-null   int8 
 1   district   2238 non-null   int16
 2   market     2238 non-null   int16
 3   commodity  2238 non-null   int16
 4   variety    2238 non-null   int16
 5   max_price  2238 non-null   int64
dtypes: int16(4), int64(1), int8(1)
memory usage: 37.3 KB


In [ ]:
np.random.state = 1
model_max = RandomForestRegressor()
X = crops_max.drop("max_price",axis=1)
Y = crops_max["max_price"]

model_max.fit(X,Y)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [ ]:
crops_max.head()

state  district  market  commodity  variety  max_price
0      0       153     246          0       17       8000
1      0       153     246         10       30       5500
2      0       153     246         18       39       8000
3      0       153     246         19      148       8000
4      0       153     246         22      148     130000

In [ ]:
model_max.predict(crops_max[:5].drop("max_price",axis=1))

array([ 9764.  ,  8324.86,  9861.05, 25732.35, 92490.  ])

In [ ]:
from sklearn.model_selection import GridSearchCV
grid_max = {"max_depth":[4,5,6],
            "max_features":[3,4,5],
            "max_samples":[2,4,6,8,10],
            "n_estimators":[20,40,60,80,100]}
grid_max_model = GridSearchCV(RandomForestRegressor(),param_grid=grid_max,scoring="neg_root_mean_squared_error",cv=5,verbose=True,n_jobs=-1)
grid_max_model.fit(X,Y)

Fitting 5 folds for each of 225 candidates, totalling 1125 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done 164 tasks      | elapsed:   10.4s
[Parallel(n_jobs=-1)]: Done 764 tasks      | elapsed:   49.2s
[Parallel(n_jobs=-1)]: Done 1125 out of 1125 | elapsed:  1.2min finished


GridSearchCV(cv=5, error_score=nan,
             estimator=RandomForestRegressor(bootstrap=True, ccp_alpha=0.0,
                                             criterion='mse', max_depth=None,
                                             max_features='auto',
                                             max_leaf_nodes=None,
                                             max_samples=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=100, n_jobs=None,
                                             oob_score=False, random_state=None,
                                             verbose=0, warm_start=False),
             iid='deprecated', n_jo

In [ ]:
len(X)

2238

In [ ]:
Y.tail()

2233     570
2234    3650
2235    4600
2236    3550
2237    2125
Name: max_price, dtype: int64

In [ ]:
grid_max_model.predict(X[2233:])

array([2287.35 , 2264.225, 3057.525, 2759.5  , 2980.25 ])

In [ ]:
model_max.predict(crops_max[2233:].drop("max_price",axis=1))

array([ 652.49, 3476.99, 4506.63, 3446.9 , 1975.99])

In [ ]:
import joblib
filename = 'max_price_model.sav'
joblib.dump(model_max, filename)

['max_price_model.sav']

In [ ]:
crops.head()

state       district  ... max_price modal_price
0  Andaman and Nicobar  South Andaman  ...      8000        7000
1  Andaman and Nicobar  South Andaman  ...      5500        5000
2  Andaman and Nicobar  South Andaman  ...      8000        7000
3  Andaman and Nicobar  South Andaman  ...      8000        7000
4  Andaman and Nicobar  South Andaman  ...    130000      120000

[5 rows x 9 columns]

In [ ]:
state = set()
for label in crops.values:
  state.add(label[4])

In [ ]:
print(state)

{'GCH', 'Elephant Yam (Suran)', 'Coarse', 'Drumstick', 'Cluster Beans', 'Suvarnagadde', '1001', 'Arkasheela Mattigulla', 'Beelary-Red', 'Dry', 'Methi', 'Whole', 'Banana - Green', 'Raddish', 'Common', 'Knool Khol', 'ADT 43', 'Beedi', 'Green Peas', 'Green Gram Dal', 'Bitter Gourd', 'Orange', 'Cucumbar', 'MCU 5', 'Hybrid/Local', 'Paddy Coarse', 'Cabbage', 'Chilly Capsicum', 'Bulb', 'White Pumpkin', 'Peas(Dry)', 'Squash(Chappal Kadoo)', 'Mustard', '95/5', 'Pommani', 'Kala Masoor New', 'Plum', 'Black Gram (Whole)', 'Papaya', 'Robusta', 'Lemon', 'Nagpuri', 'Raw', 'Deshi', 'Ponni', 'Annabesahai', 'Beete (Rose)', 'Broken Rice', 'Laha(Sarsib)', '2nd Sort', 'Chini', 'Masoor Gola', 'Supari', 'Badshah', 'Ratnachudi (718 5-749)', 'Masuri', 'Colacasia', 'Ghee', 'Potato', 'III', 'Ratna', 'Tinda', 'New Variety', 'Spinach', 'Disara', 'Yellow', 'Green Chilly', 'Round/Long', 'Beans (Whole)', 'Kalyan', 'Carrot', 'Round', 'Pigeon Pea (Arhar Fali)', 'Local', 'Local(Raw)', 'Finger', 'Nasik', 'Black', 'Sponge